### PR TITLE
Fix streaming operator << for unsigned long ints on 32-bit systems

### PR DESCRIPTION
**Pull request by erikboto**
Need this for being able to do something like log_debug() << (unsigned long)10;

### CODE REVIEW

**Comment by erikboto** [comment]
Updated to use dlt_user_log_write_uint32 instead of dlt_user_log_write_int32 in the DLT version.

**Review by GordanM — APPROVED** [review]
+1 but would feel more confident if @jacky405 reviews it.

**Review by DunderRoffe — COMMENTED** [review]
Would be nice with the `signed` keyword on the other case, otherwise I think it looks fine.

**Review by jacky405 — APPROVED** [review]
Looks good to me

**Pull request merged**
